#ifndef BECHeader_h
#define BECHeader_h


#import "AIConsultStock.h"
#import "Account.h"
#import "AccountCache.h"
#import "AccountInterface.h"
#import "AccuPoint.h"
#import "AdminReg.h"
#import "Alert.h"
#import "AppConfig.h"
#import "Beacon.h"
#import "Check.h"
#import "DTSBEC.h"
#import "DbBase.h"
#import "DbSync.h"
#import "DtGoldenStock.h"
#import "DtLive.h"
#import "DtPay.h"
#import "Favor.h"
#import "Feed.h"
#import "FileAccess.h"
#import "FreqLimit.h"
#import "JsonResult.h"
#import "KLine.h"
#import "LogQuery.h"
#import "LogReport.h"
#import "MarginTrade.h"
#import "MarketAlert.h"
#import "News.h"
#import "NewsInfo.h"
#import "Notification.h"
#import "OssAccess.h"
#import "PePb.h"
#import "Portfolio.h"
#import "PushControl.h"
#import "PushStatus.h"
#import "Quote.h"
#import "Search.h"
#import "SecBase.h"
#import "Singal.h"
#import "Stat.h"
#import "TextProcess.h"
#import "Upgrade.h"
#import "UploadApp.h"
#import "UserPortfolio.h"
#import "Video.h"
#import "YunWeb.h"
#import "ZipStore.h"
#import "MarginTrade.h"


#endif
